/** Remaining Clausura 2026 matches (fecha 10 leftover + 11–16). Home vs away, ESPN team ids. */
const T = {
  boca: "5",
  estudiantes: "8",
  independiente: "11",
  lanus: "12",
  newells: "14",
  sanLorenzo: "18",
  talleres: "19",
  union: "20",
  velez: "21",
  instituto: "2975",
  platense: "7764",
  defensa: "8950",
  gimnasiaM: "11972",
  central: "11989",
  riestra: "17702",
  argentinos: "3",
  belgrano: "4",
  gimnasia: "9",
  huracan: "10",
  racing: "15",
  river: "16",
  rosario: "17",
  banfield: "235",
  tigre: "7767",
  aldosivi: "9739",
  rivadavia: "9744",
  tucuman: "9785",
  barracas: "10060",
  sarmiento: "10158",
  estudiantesRC: "19685",
} as const;

export type FixtureGame = {
  round: number;
  homeId: string;
  awayId: string;
  label: string;
};

export function fixtureId(game: FixtureGame): string {
  return `r${game.round}-${game.homeId}-${game.awayId}`;
}

export const ROUND_LABELS: Record<number, string> = {
  10: "Fecha 10 · resto",
  11: "Fecha 11 · 2 al 4 de oct",
  12: "Fecha 12 · 11 de oct",
  13: "Fecha 13 · 18 de oct",
  14: "Fecha 14 · 25 de oct",
  15: "Fecha 15 · 1 de nov",
  16: "Fecha 16 · 8 de nov",
};

function r(round: number, homeId: string, awayId: string, label: string): FixtureGame {
  return { round, homeId, awayId, label };
}

export const REMAINING_FIXTURE: FixtureGame[] = [
  r(10, T.sanLorenzo, T.boca, "San Lorenzo vs Boca"),
  r(10, T.platense, T.newells, "Platense vs Newell's"),
  r(10, T.rosario, T.argentinos, "Central vs Argentinos"),
  r(10, T.belgrano, T.estudiantesRC, "Belgrano vs Est. (RC)"),
  r(10, T.velez, T.tigre, "Vélez vs Tigre"),
  r(10, T.aldosivi, T.tucuman, "Aldosivi vs Atl. Tucumán"),
  r(10, T.barracas, T.rivadavia, "Barracas vs Ind. Rivadavia"),
  r(10, T.lanus, T.estudiantes, "Lanús vs Estudiantes"),

  r(11, T.independiente, T.instituto, "Independiente vs Instituto"),
  r(11, T.rivadavia, T.gimnasia, "Ind. Rivadavia vs Gimnasia"),
  r(11, T.defensa, T.sanLorenzo, "Defensa vs San Lorenzo"),
  r(11, T.boca, T.union, "Boca vs Unión"),
  r(11, T.sarmiento, T.river, "Sarmiento vs River"),
  r(11, T.talleres, T.belgrano, "Talleres vs Belgrano"),
  r(11, T.huracan, T.aldosivi, "Huracán vs Aldosivi"),
  r(11, T.tucuman, T.barracas, "Atl. Tucumán vs Barracas"),
  r(11, T.argentinos, T.tigre, "Argentinos vs Tigre"),
  r(11, T.estudiantesRC, T.racing, "Est. (RC) vs Racing"),
  r(11, T.newells, T.lanus, "Newell's vs Lanús"),
  r(11, T.riestra, T.central, "Riestra vs C. Córdoba"),
  r(11, T.estudiantes, T.gimnasiaM, "Estudiantes vs Gimnasia (M)"),
  r(11, T.velez, T.platense, "Vélez vs Platense"),
  r(11, T.banfield, T.rosario, "Banfield vs Central"),

  r(12, T.tigre, T.banfield, "Tigre vs Banfield"),
  r(12, T.gimnasia, T.tucuman, "Gimnasia vs Atl. Tucumán"),
  r(12, T.lanus, T.velez, "Lanús vs Vélez"),
  r(12, T.gimnasiaM, T.newells, "Gimnasia (M) vs Newell's"),
  r(12, T.union, T.defensa, "Unión vs Defensa"),
  r(12, T.talleres, T.independiente, "Talleres vs Independiente"),
  r(12, T.racing, T.belgrano, "Racing vs Belgrano"),
  r(12, T.aldosivi, T.sarmiento, "Aldosivi vs Sarmiento"),
  r(12, T.river, T.estudiantesRC, "River vs Est. (RC)"),
  r(12, T.instituto, T.boca, "Instituto vs Boca"),
  r(12, T.rosario, T.rivadavia, "Central vs Ind. Rivadavia"),
  r(12, T.platense, T.argentinos, "Platense vs Argentinos"),
  r(12, T.central, T.estudiantes, "C. Córdoba vs Estudiantes"),
  r(12, T.barracas, T.huracan, "Barracas vs Huracán"),
  r(12, T.sanLorenzo, T.riestra, "San Lorenzo vs Riestra"),

  r(13, T.platense, T.lanus, "Platense vs Lanús"),
  r(13, T.sarmiento, T.barracas, "Sarmiento vs Barracas"),
  r(13, T.rivadavia, T.tigre, "Ind. Rivadavia vs Tigre"),
  r(13, T.boca, T.talleres, "Boca vs Talleres"),
  r(13, T.velez, T.gimnasiaM, "Vélez vs Gimnasia (M)"),
  r(13, T.riestra, T.union, "Riestra vs Unión"),
  r(13, T.estudiantes, T.sanLorenzo, "Estudiantes vs San Lorenzo"),
  r(13, T.estudiantesRC, T.aldosivi, "Est. (RC) vs Aldosivi"),
  r(13, T.racing, T.independiente, "Racing vs Independiente"),
  r(13, T.tucuman, T.rosario, "Atl. Tucumán vs Central"),
  r(13, T.huracan, T.gimnasia, "Huracán vs Gimnasia"),
  r(13, T.belgrano, T.river, "Belgrano vs River"),
  r(13, T.newells, T.central, "Newell's vs C. Córdoba"),
  r(13, T.banfield, T.argentinos, "Banfield vs Argentinos"),
  r(13, T.defensa, T.instituto, "Defensa vs Instituto"),

  r(14, T.aldosivi, T.belgrano, "Aldosivi vs Belgrano"),
  r(14, T.instituto, T.riestra, "Instituto vs Riestra"),
  r(14, T.argentinos, T.rivadavia, "Argentinos vs Ind. Rivadavia"),
  r(14, T.union, T.estudiantes, "Unión vs Estudiantes"),
  r(14, T.independiente, T.boca, "Independiente vs Boca"),
  r(14, T.barracas, T.estudiantesRC, "Barracas vs Est. (RC)"),
  r(14, T.sanLorenzo, T.newells, "San Lorenzo vs Newell's"),
  r(14, T.gimnasiaM, T.platense, "Gimnasia (M) vs Platense"),
  r(14, T.tigre, T.tucuman, "Tigre vs Atl. Tucumán"),
  r(14, T.rosario, T.huracan, "Central vs Huracán"),
  r(14, T.river, T.racing, "River vs Racing"),
  r(14, T.gimnasia, T.sarmiento, "Gimnasia vs Sarmiento"),
  r(14, T.talleres, T.defensa, "Talleres vs Defensa"),
  r(14, T.banfield, T.lanus, "Banfield vs Lanús"),
  r(14, T.central, T.velez, "C. Córdoba vs Vélez"),

  r(15, T.newells, T.union, "Newell's vs Unión"),
  r(15, T.estudiantesRC, T.gimnasia, "Est. (RC) vs Gimnasia"),
  r(15, T.estudiantes, T.instituto, "Estudiantes vs Instituto"),
  r(15, T.defensa, T.independiente, "Defensa vs Independiente"),
  r(15, T.tucuman, T.argentinos, "Atl. Tucumán vs Argentinos"),
  r(15, T.racing, T.aldosivi, "Racing vs Aldosivi"),
  r(15, T.boca, T.river, "Boca vs River"),
  r(15, T.sarmiento, T.rosario, "Sarmiento vs Central"),
  r(15, T.riestra, T.talleres, "Riestra vs Talleres"),
  r(15, T.belgrano, T.barracas, "Belgrano vs Barracas"),
  r(15, T.platense, T.central, "Platense vs C. Córdoba"),
  r(15, T.rivadavia, T.banfield, "Ind. Rivadavia vs Banfield"),
  r(15, T.velez, T.sanLorenzo, "Vélez vs San Lorenzo"),
  r(15, T.lanus, T.gimnasiaM, "Lanús vs Gimnasia (M)"),
  r(15, T.huracan, T.tigre, "Huracán vs Tigre"),

  r(16, T.boca, T.defensa, "Boca vs Defensa"),
  r(16, T.independiente, T.riestra, "Independiente vs Riestra"),
  r(16, T.rosario, T.estudiantesRC, "Central vs Est. (RC)"),
  r(16, T.central, T.lanus, "C. Córdoba vs Lanús"),
  r(16, T.barracas, T.racing, "Barracas vs Racing"),
  r(16, T.sanLorenzo, T.platense, "San Lorenzo vs Platense"),
  r(16, T.talleres, T.estudiantes, "Talleres vs Estudiantes"),
  r(16, T.tigre, T.sarmiento, "Tigre vs Sarmiento"),
  r(16, T.aldosivi, T.river, "Aldosivi vs River"),
  r(16, T.gimnasiaM, T.rivadavia, "Gimnasia (M) vs Ind. Rivadavia"),
  r(16, T.instituto, T.newells, "Instituto vs Newell's"),
  r(16, T.gimnasia, T.belgrano, "Gimnasia vs Belgrano"),
  r(16, T.banfield, T.tucuman, "Banfield vs Atl. Tucumán"),
  r(16, T.union, T.velez, "Unión vs Vélez"),
  r(16, T.argentinos, T.huracan, "Argentinos vs Huracán"),
];
